
# >> 网站基本配置 ---------------------------------------------------------------

title: 幻凡ss #网站标题
description: 专注Java • 分享生活 • 记录人生 #网站说明
keywords: java,IT,幻凡ss,幻凡 #网站关键词（用于搜索引擎收录,添加多个关键词请用英文逗号分隔）
language: zh-CN #网站语言（默认中文 zh-CN即可）
shortcut_icon: /favicon.ico #浏览器中地址栏或标签页中显示的图标，尺寸一般为16 x 16像素大小，后缀为ico格式
icon: /img/icon.png #可放的格式可为PNG\GIF\JPEG，尺寸一般为64x64或更大
changeTitle: 咦，页面崩溃了！ #切换标签页后更改的标题
copyTips: #复制网页时弹出提示窗口的内容
  enable: false #是否启用
  title: 复制成功 #窗口标题
  content: 如需转载文章请注意声明原文出处，谢谢合作！ #提示信息

## 网站建立日期 用于在网站底部显示运行时间（24小时制）
runtime: 
  enable: true  #是否启用
  span: 本站已稳定运行：  #开头显示的文本
  year: 2018  #年
  month: 4  #月
  day: 01  #日
  hour: 01  #时
  minute: 01  #分
  second: 01  #秒

# 网址配置
url:  https://hfanss.com #填写你当前博客的网站域名 注意！！！ 域名必须正确填写，且带协议头(http://或https://)。若不填域名或填写有误则一些模块则无法使用！(比如文章分享)
root: /     # 如果您的站点放在子目录中，请将URL设置为“http://yoursite.com/子目录名称”，将root设置为“/子目录名称/”
permalink: :year/:title.html
permalink_defaults:

# 显示神兽图腾（纯娱乐性质，无其他实际意义,如需开启请关闭html压缩，否则无显示效果）
## 是否在网页源代码中显示神兽图腾 true为显示，false即为不显示
totem: false

# >> 主题配置 ---------------------------------------------------------------------

# 轮播图配置

## url是每个轮播图的点击链接，如果不设置链接请填写javascript:void(0) img是轮播图图片，图片是800 x 300 px的大小banner 可以填图片地址或图片在资源中的相对路径
## 如果不使用轮播图时，把carousel下的配置全部注释或者删除即可

#carousel:
#  - url: javascript:void(0)
#    img: /img/banner-1.png
#  - url: javascript:void(0)
#    img: /img/banner-2.png
#  - url: javascript:void(0)
#    img: /img/banner-3.png  

#导航栏logo（建议240 x 120 px像素）
nav_logo: /img/Blog_logo.png

# 导航栏
# 导航栏的菜单数量建议不超过八个，菜单名不宜过长。

nav_menu:
  - name: 首页 #导航栏名称
    slug: home # 页面所在文件夹名称
    url: / #页面路径
  - name: 时间轴
    slug: archives
    url: /archives/index.html
#  - name: 资源分享
#    slug: ziyuanfenx
#    url: /ziyuanfenx/index.html
  - name: 开源项目
    slug: open
    url: /tags/开源项目/index.html 
#  使用电影这个 需要安装豆瓣插件
#  - name: 电影
#    slug: movies
#    url: /movies/index.html 
  - name: 友链
    slug: links
    url: /links/index.html
  - name: 留言板
    slug: comment
    url: /comment/index.html

# 右边的小窗口，不想显示哪一项的注释掉对应的即可
widgets:
  # 博主信息，显示个人头像、格言、社交信息等
  author:
    enable: true #是否启用头像 false为不显示
    avatar: /img/author.png # 头像，如果config中已经设置avatar了，这里可以不用写
    title: 幻凡ss # 博客名、头衔等等，居中显示
    motto:  IT小青年 | hfanss.com # 格言座右铭等等
    conum: '>20' #评论数 --------------------------------------------------------------------------------------------------< 更新条目


  # -----------------------------------------------------------------------------------------------------------------------< 更新条目
  # 社交信息栏 
  social: 
    enable: true # 是否在头像栏下方显示社交信息栏


  # 设置社交信息请打开 博客根目录\themes\material-plus\layout\_widget\author.ejs 文件进行修改 

  # 公告
  ## name是公告标题 content是公告的内容 type是在弹出窗口的上方显示的图标，可选类型有： success (成功) 、error (错误)、 warning (警告) 、 info (信息)，
  ## type不填即不会显示图标
  ## 在填写公告内容时不要换行，以免编译出错，换行请用换行符\n代替。
  #notice:
  #- name: 博客夜间模式用法 
  #  content: 本站支持夜间模式，以下是各个快捷键的用法\n\nAlt+Z：开启夜间模式  Alt+X：关闭夜间模式\nAlt+↑：增加亮度 Alt+↓：降低亮度
  #  type: 

  # 显示文章分类
  categories: true

  # 显示云标签
  tagcloud: false

  # 显示目录（在文章中设置toc:false可以隐藏单篇文章的目录）
  toc: true

  # 显示网易云歌单
  musicid:  2270688529 #填写歌单号

  # 热门推荐
  ## 若不想显示侧栏的热门推荐，注释即可

  links:
  - name: Maupassant主题优化、屠城hexo主题优化版
    avatar: /img/hotrec-1.png
    url: /2018/Maupassant主题、屠城主题优化版.html

  - name: 腾讯云COS图床制作
    avatar: /img/hotrec-2.png
    url: /2018/腾讯云COS图床制作.html

  - name: 码云+hexo搭建个性博客
    avatar: /img/hotrec-3.png
    url: /2018/码云+hexo搭建个性博客.html

  - name: hexo博客常用插件及教程
    avatar: /img/hotrec-all.png
    url: /2018/hexo博客常用插件及教程.html


beian: 豫ICP备18024944号
qq: https://wpa.qq.com/msgrd?v=3&uin=2158798&site=qq&menu=yes
mail: https://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=8JiWkZ6DsJafiJ2RmZzek5_d #邮我 地址
github: https://github.com/hfanss/
csdn: https://me.csdn.net/q2158798

# 顶部公告
topnotice:
  enable: false #是否启用公告 false为不启用
  img: /img/top-notice-img.png #顶部公告图标地址 默认为top-notice-img.png（小喇叭图标）
  content: #顶部公告内容，字数不宜过长
  link: javascript:void(0) #文字链接 如果不设置链接请填写javascript:void(0)

# 底部版权信息
copyrightIcon: true #显示版权C图标
copyright: 2018 幻凡ss #版权信息

# 底部友链推荐
bottomlink: 
  - name:  幻凡ss
    url: hfanss.com

# ----------------------------------------------------------------------------------------------------------------------< 更新条目
# 是否在底部显示图片，图片请到img文件夹替换，制作尺寸为640x640px
footerpic: false

# 是否在底部显示鸣谢栏目
## 若不想显示注释即可
# footerthank: 
#   - name: HEXO
#     url: https://hexo.io
#   - name: MaterialPlus
#     url: https://mp.wushile.top 
#   - name: Coding
#     url: https://www.coding.net

# 文章摘录配置 （为了能更好的配置摘录，建议文章摘录的内容不要少于30个字符）
## 设置在PC端显示的文章摘录长度，单位：字符
zhailu_length: 90
## 设置在手机端显示的文章摘录长度，单位：字符
zhailu_length_phone: 80

# 文章分享配置
share: 
  # 分享标题
  title:  幻凡ss #可以是博客名称或者个人昵称
  pic:  /img/author.png #可以填网站logo或导航栏logo图片地址 必须填绝对路径

# 网站地图
sitemap: 
  path: sitemap.xml

# 百度统计key，百度统计中的代码获取  hm.src  最后面的后缀
baidu_analytics_key: 4e950a5dd7243ac97e882fe04d3fa1f7
# 百度自动推送
baidu_push: true

# 推荐文章
recommended_posts:
  autoDisplay: false # 自动在文章底部显示推荐文章，如果你使用Material-X主题，这里要设置为false。
  server: https://api.truelaurel.com # 后端推荐服务器地址
  timeoutInMillis: 10000 # 服务时长，超过此时长，则使用离线推荐模式
  excludePattern: []
  titleHtml: <h4>推荐文章</h4> #自定义标题
  internalLinks: 3 # 内部文章显示数量
  externalLinks: 2 # 外部文章显示数量
  fixedNumber: false


# 评论设置
## 来必力评论 
#livere_uid:  ##填写在来在必力平台注册并申请来的UID

## 畅言评论
# changyan: 
#   enable: true
#   appId: 
#   conf: 

#valine评论
valine: 
  enable: true
  appId: 5GMAO3V5MqR
  appkey: f6Ve1tpYqYS
  avatar: monsterid ##默认头像 参考 https://valine.js.org/avatar.html
  placeholder: 　 ## 留言板预设内容
  pageSize: 10 ##每页显示条数

# 搜索配置 
## Search 确保_config中只有一个search，否则会冲突。
search:
  enable: true
  service: hexo
# google
google_api_key:
google_engine_id:
# algolia
algolia_app_id:
algolia_api_key:
algolia_index_name:
# azure
azure_service_name:
azure_index_name:
azure_query_key:
# baidu
baidu_api_id:

# >> 网站高级配置 ---------------------------------------------------------------------

# Security
##
encrypt:
    enable: true

# 目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 写作
new_post_name: :title.md # 新建的文章的文件名
default_layout: post
titlecase: false # 将标题转换为标题
external_link: true # 在新标签中打开外部链接
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# 代码高亮
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# 主页设置
# path: 博客索引页面的根路径 (default = '')
# per_page: 每页显示的帖子 (0 = disable pagination)
# order_by: 文章列表的排列顺序. (默认情况下按日期降序排序)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类和标签
default_category: uncategorized
category_map:
tag_map:

# 日期 / 时间格式
## Hexo使用Moment.js来解析和显示日期
## 您可以自定义日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD-dddd
time_format: HH:mm:ss

# 分页
## 将per_page设置为0可禁用分页
per_page: 10
pagination_dir: page

# 扩展
## 插件: https://hexo.io/plugins/
## 主题: https://hexo.io/themes/
theme: material-plus

less:
  compress: truelaurel

# -----------------------------------------------------------------------------------------------------------------------< 更新条目
## 代码压缩 
all_minifier: true
image_minifier:
  enable: false
css_minifier: 
  enable: false

# 部署
## 参考文档: https://hexo.io/docs/deployment.html


## 部署
deploy:
# coding
- type: git    
  repository: https://hexo.io/docs/deployment.html
  branch: master
## 码云
- type: git
  repository: https://hexo.io/docs/deployment.html
  branch: dev


