
# >> 网站基本配置 ---------------------------------------------------------------

title: 小吴博客 #网站名称/标题
description: 提供各类原创IT技术教程与软件资讯 #网站说明
keywords: 吴施乐的博客,凉城浪徒的博客,IT博客,成功励志,前端,Android #网站关键词（用于搜索引擎收录）
language: zh-CN #网站语言（默认中文 zh-CN即可）
shortcut_icon: /favicon.ico #浏览器中地址栏或标签页中显示的图标，尺寸一般为16 x 16像素大小，后缀为ico格式
icon: /img/icon.png #可放的格式可为PNG\GIF\JPEG，尺寸一般为64x64或更大
changeTitle: 欢迎回到小吴博客 #切换标签页后更改的标题
copyTips: #复制网页时弹出提示窗口的内容
  enable: true #是否启用
  title: 复制成功 #窗口标题
  content: 如需转载文章请注意声明原文出处，谢谢合作！ #提示信息

## 网站建立日期 用于在网站底部显示运行时间（24小时制）
runtime: 
  enable: true  #是否启用
  span: 本站已稳定运行：  #开头显示的文本
  year: 2018  #年
  month: 8    #月
  day: 22  #日
  hour: 18  #时
  minute: 27  #分
  second: 00  #秒

# 网址配置
url: https://www.wushile.top #填写你的网站域名
root: /     # 如果您的站点放在子目录中，请将URL设置为“http://yoursite.com/子目录名称”，将root设置为“/子目录名称/”
permalink: article/:title.html
permalink_defaults:

# 显示神兽图腾（纯娱乐性质，无其他实际意义）
## 是否在网页源代码中显示神兽图腾 true为显示，false即为不显示
totem: true

# >> 主题配置 ---------------------------------------------------------------------

## Banner与轮播图的区别是，Banner是固定在博客首页的大图，轮播图就不必赘述了。
## 还请注意！！！ Banner和轮播图不可同时启用，否则布局会出错！

# Banner配置
fixed_banner: 
  enable: false #是否启用banner
  img: https://img.vim-cn.com/bd/b687c56f6f756ebd35070189c099c5d2ff9419.png  ## 880 x 300 px 的banner 可以填图片地址或图片在资源中的相对路径

# 轮播图配置 
## url是每个轮播图的点击链接，如果不设置链接请填写javascript:void(0) img是轮播图图片，图片是800 x 300 px的大小banner 可以填图片地址或图片在资源中的相对路径
## 如果不使用轮播图时，把carousel下的配置全部注释或者删除即可

carousel:
  - url: javascript:void(0)
    img: /img/lb_1.png
  - url: http://shang.qq.com/wpa/qunwpa?idkey=5a27807266d30155dff493dc101246e233d1ab34b1b1c950cb0698f3e84c4330
    img: /img/lb_2.png
  - url: https://www.wushile.top/article/article-top.html
    img: /img/lb_3.png  
#导航栏logo（建议240 x 120 px像素）
nav_logo: /img/XiaoWuBlog_logo_240x120.png

# 导航栏
# 导航栏的菜单数量建议不超过八个，菜单名不宜过长。

nav_menu:
  - name: 文章 #导航栏名称
    slug: home # 页面所在文件夹名称
    url: / #页面路径
  - name: 归档
    slug: archives
    url: /archives/index.html
  - name: 资源
    slug: resources
    url: /resources/index.html
  - name: 友链
    slug: links
    url: /links/index.html
  - name: 加群
    slug: jiaqun
    url: /jiaqun/index.html
  - name: 曝光台
    slug: baoguangtai
    url: /baoguangtai/index.html
  - name: 关于
    slug: about
    url: /about/index.html
  - name: 声明
    slug: statement
    url: /statement/index.html

# 右边的小窗口，不想显示哪一项的注释掉对应的即可
widgets:
  # 博主信息，显示个人头像、格言、社交信息等
  author:
    enable: true #是否启用头像 false为不显示
    avatar: /img/author.png # 头像，如果config中已经设置avatar了，这里可以不用写
    title: 凉 城 浪 徒 # 博客名、头衔等等，居中显示
    motto: 一名满腔热血的IT技术爱好者 # 格言座右铭等等
    social: true # 是否显示社交信息

  # 显示文章分类
  categories: true

  # 显示云标签
  tagcloud: true

  # 显示目录（在文章中设置toc:false可以隐藏单篇文章的目录）
  toc: true

  # 显示网易云歌单
  musicid:  #填写歌单号

  # 热门推荐
  links:
  - name: 博客背景美化
    avatar: /img/hotrec-1.png
    url: /article/201810212028.html

  - name: Web开发和移动开发两种行业的选择
    avatar: /img/hotrec-2.png
    url: /article/201810031737.html

  - name: 小吴原创-Martial X实现文章分享
    avatar: /img/hotrec-3.png
    url: /article/201811192203.html

  - name: 介绍下我的工作室
    avatar: /img/hotrec-all.png
    url: /article/201810202211.html

  - name: 现在的电脑还需要安装杀毒软件吗？
    avatar: /img/hotrec-all.png
    url: /article/201812061317.html

  - name: 网红“面筋哥”被嘲讽事件点评
    avatar: /img/hotrec-all.png
    url: /article/201809161905.html

  - name: js实现网站的两个小功能
    avatar: /img/hotrec-all.png
    url: /article/201811031638.html

  - name: 普通电脑能否当做服务器正常使用？
    avatar: /img/hotrec-all.png
    url: /article/201810151309.html


# 公告
## name是公告标题 content是公告的内容 type是在弹出窗口的上方显示的图标，可选类型有： success (成功) 、error (错误)、 warning (警告) 、 info (信息)，
## type不填即不会显示图标
## 在填写公告内容时不要换行，以免编译出错，换行请用换行符\n代替。
  notice:
  - name: 博客夜间模式用法 
    content: 本站支持夜间模式，以下是各个快捷键的用法\n\nAlt+Z：开启夜间模式  Alt+X：关闭夜间模式\nAlt+↑：增加亮度 Alt+↓：降低亮度
    type: 
  - name: 本站备用链接
    content: 本站备用链接：https://sub.wushile.top
    type: 

# 顶部公告
topnotice:
  enable: true #是否启用公告 false为不启用
  img: /img/top-notice-img.png #顶部公告图标地址 默认为top-notice-img.png（小喇叭图标）
  content: 2月18日起博客更新周期可能会变长甚至暂停更新，届时会再次进行通知 #顶部公告内容，字数不宜过长
  btn_name: 查看详情  #链接名称  如果不填写链接名称，则公告后面的链接文字不会显示
  btn_link: /article/26.html #文字链接

# 底部版权信息
copyrightIcon: true #显示版权C图标
copyright: 2019 小吴博客 版权所有 #版权信息

# 底部友链推荐
bottomlink: 
  - name: xaoxuu'blog
    url: https://blog.xaoxuu.com
  - name: 小俊博客
    url: https://www.xjdog.cn
  - name: MicDZ's blog
    url: https://www.micdz.cn/

# 启用粒子网背景特效
bg_nest:  
  enable: false    #是否启用
  color: 0,0,0    #线条颜色 (RGB数值)
  opacity: 0.5    #线条透明度（值的范围为0~1）
  zIndex: -1    #所在层的位置 （默认-1即可）
  count: 150      #线条的总数量

# 文章摘录配置 （为了能更好的配置摘录，建议文章摘录的内容不要少于30个字符）
## 设置在PC端显示的文章摘录长度，单位：字符
zhailu_length: 90
## 设置在手机端显示的文章摘录长度，单位：字符
zhailu_length_phone: 80

# 文章分享配置
share: 
  # 分享标题
  title: 小吴博客 #可以是博客名称或者个人昵称
  pic: https://www.wushile.top/img/XiaoWuBlog_logo_240x120.png #可以填网站logo或导航栏logo图片地址

# 网站地图
sitemap: 
  path: sitemap.xml

# 百度统计key
baidu_analytics_key: 5090deb2c048d61b7e93d6f65edd5f96
# 百度自动推送
baidu_push: true

# 推荐文章
recommended_posts:
  autoDisplay: false # 自动在文章底部显示推荐文章，如果你使用Material-X主题，这里要设置为false。
  server: https://api.truelaurel.com # 后端推荐服务器地址
  timeoutInMillis: 10000 # 服务时长，超过此时长，则使用离线推荐模式
  excludePattern: []
  titleHtml: <h4>推荐文章</h4> #自定义标题
  internalLinks: 3 # 内部文章显示数量
  externalLinks: 2 # 外部文章显示数量
  fixedNumber: false


# 评论设置
## 来必力评论 
livere_uid: MTAyMC8zOTcwNC8xNjIzMQ== ##填写在来在必力平台注册并申请来的UID

## 畅言评论
# changyan: 
#   enable: true
#   appId: cytiBEfFo
#   conf: prod_0e53369135c947c1e08e66a7f10b5d50

# 搜索配置 
## Search 确保_config中只有一个search，否则会冲突。
search:
  enable: true
  service: hexo
# google
google_api_key:
google_engine_id:
# algolia
algolia_app_id:
algolia_api_key:
algolia_index_name:
# azure
azure_service_name:
azure_index_name:
azure_query_key:
# baidu
baidu_api_id:

# >> 网站高级配置 ---------------------------------------------------------------------

# Security
##
encrypt:
    enable: true

# 目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 写作
new_post_name: :title.md # 新建的文章的文件名
default_layout: post
titlecase: false # 将标题转换为标题
external_link: true # 在新标签中打开外部链接
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

# 代码高亮
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# 主页设置
# path: 博客索引页面的根路径 (default = '')
# per_page: 每页显示的帖子 (0 = disable pagination)
# order_by: 文章列表的排列顺序. (默认情况下按日期降序排序)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类和标签
default_category: uncategorized
category_map:
tag_map:

# 日期 / 时间格式
## Hexo使用Moment.js来解析和显示日期
## 您可以自定义日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD-dddd
time_format: HH:mm:ss

# 分页
## 将per_page设置为0可禁用分页
per_page: 10
pagination_dir: page

# 扩展
## 插件: https://hexo.io/plugins/
## 主题: https://hexo.io/themes/
theme: material-plus

less:
  compress: truelaurel

# HTML压缩
html_minifier:  
  removeComments: true
  collapseWhitespace: true
  collapseBooleanAttributes: true
  removeEmptyAttributes: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true
  
# 图片压缩
imagemin:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false为不启用


# 部署
## 参考文档: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:wushile/wushile.github.io.git,master
    coding: git@git.dev.tencent.com:wesley184/wesley184.git,master


# deploy:
#   type: git    
#   repository: #你的SSH地址
#   branch: master
